let products=[
    {
        productImg:["./Asset/Shop-all-product/DEWTOPIA 25perc ACID FLASH FACIAL MASK.jfif"],
        introduceText:"COMING SOON",
        productName:"DEWTOPIA 25% ACID FLASH FACIAL MASK",
        catalogue:"MASK",
        status:"Notify Me",
        rating:5,
        size:[1.7],
        originalPrice:[],
        price:[],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT + EYE CREME.jfif"],
        introduceText:"BESTSELLER",
        productName:"BANANA BRIGHT+ EYE CRÈME",
        catalogue:"EYES + LIP CARE",
        status:"Available",
        rating:4,
        size:[0.5],
        originalPrice:[],
        price:["1139900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/STRENGTH TRAINER PEPTIDE BOOST MOISTURIZER.jfif","./Asset/Shop-all-product/STRENGTH TRAINER PEPTIDE BOOST MOISTURIZER  05oz.jfif"],
        introduceText:"BESTSELLER + BACK IN STOCK",
        productName:"STRENGTH TRAINER PEPTIDE BOOST MOISTURIZER",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[1.7,0.5],
        originalPrice:[],
        price:["1384200","542800"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT FACE PRIMER.jfif"],
        introduceText:"",
        productName:"BANANA BRIGHT FACE PRIMER",
        catalogue:"SERUM",
        status:"Available",
        rating:4.5,
        size:[1],
        originalPrice:[],
        price:["1085600"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT SUN-KISSED SELF TANNER + MAKEUP PRIMER.jfif"],
        introduceText:"LIMITED EDITION + BACK IN STOCK",
        productName:"BANANA BRIGHT SUN-KISSED SELF-TANNER + MAKEUP PRIMER",
        catalogue:"EYES + LIP CARE",
        status:"Available",
        rating:4.5,
        size:[1],
        originalPrice:[],
        price:["1085600"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT + VITAMIN CC STICK.jfif"],
        introduceText:"CHOOSE YOUR SHADE",
        productName:"BANANA BRIGHT+ VITAMIN CC STICK",
        catalogue:"EYES + LIP CARE",
        status:"Available",
        rating:4.5,
        size:[1],
        originalPrice:[],
        price:["922800"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/POUT PRESERVE PEPTIDE LIP TREATMENT.jfif"],
        introduceText:"NEW",
        productName:"POUT PRESERVE PEPTIDE LIP TREATMENT",
        catalogue:"EYES + LIP CARE",
        status:"Available",
        rating:4.5,
        size:[0.4],
        originalPrice:[],
        price:["597100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW ACCELERATORS MINI DAILY SKINCARE STARTER SET.jfif"],
        introduceText:"MINI BESTSELLERS | ALL SKIN TYPES",
        productName:"GLOW ACCELERATORS MINI DAILY SKINCARE STARTER SET",
        catalogue:"SET KIT",
        status:"Available",
        rating:5,
        size:[],
        originalPrice:["2469800"],
        price:["597100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/TRUTH SERUM.jfif"],
        introduceText:"BESTSELLER",
        productName:"TRUTH SERUM",
        catalogue:"SERUM",
        status:"Available",
        rating:4.5,
        size:[1],
        originalPrice:[],
        price:["1519900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT VITAMIN C SERUM.jfif"],
        introduceText:"BESTSELLER",
        productName:"BANANA BRIGHT VITAMIN C SERUM",
        catalogue:"SERUM",
        status:"Available",
        rating:4,
        size:[1],
        originalPrice:[],
        price:["1927000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/LET'S ET LUMINOUS + BRIGHTENING VITAMIN C ESSENTIALS SET.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌2,171,200 VALUE)",
        productName:"LET'S GET LUMINOUS+ BRIGHTENING VITAMIN C ESSENTIALS SET",
        catalogue:"KIT SET",
        status:"Available",
        rating:4.5,
        size:[],
        originalPrice:["2171200"],
        price:["1248500"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/C-RUSH BRIGHTENING GEL CREME.jfif"],
        introduceText:"BESTSELLER",
        productName:"C-RUSH BRIGHTENING GEL CRÈME",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[1.7],
        originalPrice:[],
        price:["1384200"],
        quantity:1
    }
    ,{
        productImg:["./Asset/Shop-all-product/LEMONADE SMOOTHING SCRUB 3OZ.jfif","./Asset/Shop-all-product/LEMONADE SMOOTHING SCRUB 1OZ.jfif"],
        introduceText:"BESTSELLER",
        productName:"LEMONADE SMOOTHING SCRUB",
        catalogue:"MASK",
        status:"Available",
        rating:4.5,
        size:[3,1],
        originalPrice:[],
        price:["949800","488500"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT MINERAL SUNSCREEN SPF 30.jfif"],
        introduceText:"NEW",
        productName:"BANANA BRIGHT MINERAL SUNSCREEN SPF 30",
        catalogue:"SUNSCREEN",
        status:"Full Detail",
        rating:4.5,
        size:[1.7],
        originalPrice:[],
        price:["949800"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW2OH DARK SPOT TONER.jfif","./Asset/Shop-all-product/GLOW2OH DARK SPOT TONER 2.2OZ.jfif"],
        introduceText:"BESTSELLER",
        productName:"GLOW2OH DARK SPOT TONER",
        catalogue:"TONER",
        status:"Available",
        rating:4.5,
        size:[6.5,2.2],
        originalPrice:[],
        price:["949800","515600"],
        quantity:1
    },{
        productImg:["./Asset/Shop-all-product/THE FLOW CYCLE BUNDLE FULL-SIZE DAILY ROUTINE.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌5,399,800 VALUE)",
        productName:"THE GLOW CYCLE BUNDLE FULL-SIZE DAILY ROUTINE",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["5399800"],
        price:["4043100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/TRUTH JUICE DAILY CLEANSER 5OZ.jfif","./Asset/Shop-all-product/TRUTH JUICE DAILY CLEANSER 2OZ.jfif"],
        introduceText:"BESTSELLER",
        productName:"TRUTH JUICE DAILY CLEANSER",
        catalogue:"CLEANSER",
        status:"Available",
        rating:4,
        size:[5,2],
        originalPrice:[],
        price:["895500","434200"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/DEWTOPIA 20 ACID NIGHT TREATMENT 1.7OZ.jfif","./Asset/Shop-all-product/DEWTOPIA 20 ACID NIGHT TREATMENT 1OZ.jfif"],
        introduceText:"BESTSELLER",
        productName:"DEWTOPIA 20% ACID NIGHT TREATMENT",
        catalogue:"SERUM",
        status:"Available",
        rating:4.5,
        size:[1.7,1],
        originalPrice:[],
        price:["2333600","1628100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/HYDRABARRIER NOURISHING FACE OIL.jfif"],
        introduceText:"NEW",
        productName:"HYDRABARRIER NOURISHING FACE OIL",
        catalogue:"SERUM",
        status:"Available",
        rating:4.5,
        size:[1],
        originalPrice:[],
        price:["1573900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BALANCING FORCE OIL CONTROL TONER.jfif"],
        introduceText:"BESTSELLER",
        productName:"BALANCING FORCE OIL CONTROL TONER",
        catalogue:"TONER",
        status:"Available",
        rating:4,
        size:[6.5],
        originalPrice:[],
        price:["949800"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/WRINKLE BLUR BAKUCHIOL EYE GEL CREME.jfif"],
        introduceText:"BESTSELLER",
        productName:"WRINKLE BLUR BAKUCHIOL EYE GEL CRÈME",
        catalogue:"EYES + LIP CARE",
        status:"Available",
        rating:4.5,
        size:[0.5],
        originalPrice:[],
        price:["1411000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/DEWTOPIA 5 ACID FIRMING NIGHT CREME.jfif"],
        introduceText:"NEW",
        productName:"DEWTOPIA 5% ACID FIRMING NIGHT CRÈME",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:5,
        size:[1.7],
        originalPrice:[],
        price:["1628100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/FIND YOUR BALANCE OIL CONTROL CLEANSER.jfif"],
        introduceText:"",
        productName:"FIND YOUR BALANCE OIL CONTROL CLEANSER",
        catalogue:"CLEANSER",
        status:"Available",
        rating:4.5,
        size:[5],
        originalPrice:[],
        price:["868400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/OLE GLOW ICONS SKINCARE SET.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌2,876,300 VALUE)",
        productName:"OLE GLOW ICONS SKINCARE SET",
        catalogue:"SET KIT",
        status:"Available",
        rating:4.5,
        size:[],
        originalPrice:["2876300"],
        price:["1682400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BARRIER BOOSTER ORANGE FERMENT VITAMIN C ESSENCE.jfif"],
        introduceText:"NEW",
        productName:"BARRIER BOOSTER ORANGE FERMENT VITAMIN C ESSENCE",
        catalogue:"SERUM",
        status:"Available",
        rating:4.5,
        size:[4],
        originalPrice:[],
        price:["1302500"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/COLD PLUNGE PORE REMEDY MOISTURIZER.jfif"],
        introduceText:"BESTSELLER",
        productName:"COLD PLUNGE PORE REMEDY MOISTURIZER",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[1.7],
        originalPrice:[],
        price:["1383900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW STRONG MINI MOISTURIZER + EYE CREAM DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌1,194,000 VALUE)",
        productName:"GLOW STRONG MINI MOISTURIZER + EYE CREAM DUO",
        catalogue:"SET KIT",
        status:"Available",
        rating:4.5,
        size:[],
        originalPrice:["1194000"],
        price:["678400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/STAY IN TOUCH RESTORATIVE HAND CREME.jfif"],
        introduceText:"NEW",
        productName:"STAY IN TOUCH RESTORATIVE HAND CRÈME",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4,
        size:[2.5],
        originalPrice:[],
        price:["597000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BEAMCREAM SMOOTHING BODY MOISTURIZER.jfif","./Asset/Shop-all-product/BEAMCREAM SMOOTHING BODY MOISTURIZER 1.7OZ.jfif"],
        introduceText:"",
        productName:"BEAMCREAM SMOOTHING BODY MOISTURIZER",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[6.4,1.7],
        originalPrice:[],
        price:["1031200","542700"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW CYCLE RETIN-ALT POWER SERUM.jfif"],
        introduceText:"BESTSELLER",
        productName:"GLOW CYCLE RETIN-ALT POWER SERUM",
        catalogue:"SERUM",
        status:"Available",
        rating:4,
        size:[1],
        originalPrice:[],
        price:["1628100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/PORE-BALANCE FACIAL SAUNA SCRUB.jfif"],
        introduceText:"BESTSELLER",
        productName:"PORE-BALANCE FACIAL SAUNA SCRUB",
        catalogue:"MASK",
        status:"Available",
        rating:4.5,
        size:[3.4],
        originalPrice:[],
        price:["949800"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/FIRMLY YOURS TONING DRY BODY OIL.jfif"],
        introduceText:"",
        productName:"FIRMLY YOURS TONING DRY BODY OIL",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[3.4],
        originalPrice:[],
        price:["1221100"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/COLD PLUNGE PORE MASK.jfif"],
        introduceText:"BESTSELLER",
        productName:"COLD PLUNGE PORE MASK",
        catalogue:"MASK",
        status:"Available",
        rating:4.5,
        size:[3.3],
        originalPrice:[],
        price:["1112600"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/ACIDS DONE BRIGHT SMOOTHING SKINCARE SET.jfif"],
        introduceText:"EXTRA 40% OFF",
        productName:"ACIDS DONE BRIGHT SMOOTHING SKINCARE SET",
        catalogue:"SET KIT",
        status:"Available",
        rating:4.5,
        size:[],
        originalPrice:["1194000"],
        price:["716400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BALANCE IT ALL OIL CONTROL & PORE-REFINING SET.jfif"],
        introduceText:"OILY & BLEMISH-PRONE SKIN",
        productName:"BALANCE IT ALL OIL CONTROL & PORE-REFINING SET",
        catalogue:"SET KIT",
        status:"Available",
        rating:4,
        size:[],
        originalPrice:[],
        price:["1085400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/DAY BRIGHT & SMOOTH NIGHT VITAMIN C & ACID SERUM FULL-SIZE DUO.jfif"],
        introduceText:"FINE LINES & UNEVEN TEXTURE (₫‌3,527,500 VALUE)",
        productName:"DAY BRIGHT & SMOOTH NIGHT VITAMIN C & ACID SERUM FULL-SIZE DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["3527500"],
        price:["2984900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/C-RUSH BRIGHTENING GEL CREME DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,767,800 VALUE)",
        productName:"C-RUSH BRIGHTENING GEL CRÈME DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["2767800"],
        price:["2469300"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/MOISTURE BARRIER DUO STRENGTH TRAINER MOISTURIZER & HYDRABARRIER FACE.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,876,300 VALUE)",
        productName:"MOISTURE BARRIER DUO STRENGTH TRAINER MOISTURIZER & HYDRABARRIER FACE OIL",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["2876300"],
        price:["2442200"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/STRENGTH TRAINER PEPTIDE BOOST MOISTURIZER DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,767,800 VALUE)",
        productName:"STRENGTH TRAINER PEPTIDE BOOST MOISTURIZER DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["2767800"],
        price:["2469300"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/HUNT FOR HYDRATION FULL-SIZE MOISTURIZER & EYE CREME DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,523,600 VALUE)",
        productName:"HUNT FOR HYDRATION FULL-SIZE MOISTURIZER & EYE CRÈME DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["2523600"],
        price:["2252200"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BARRIER BRIGHT MORNING TRIO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌4,423,000 VALUE)",
        productName:"BARRIER BRIGHT MORNING TRIO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["4423000"],
        price:["3744600"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/MORNING GLOW BUNDLE DAILY SKINCARE ROUTINE.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌4,070,200 VALUE)",
        productName:"MORNING GLOW BUNDLE DAILY SKINCARE ROUTINE",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["4070200"],
        price:["3391900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT ILLUMINATING EYE DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,062,300 VALUE)",
        productName:"BANANA BRIGHT ILLUMINATING EYE DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["2062300"],
        price:["1546700"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/DEWTOPIA NIGHTTIME DUO 5 ACID FIRMING NIGHT CREME & 20 ACID NIGHT TREATMENT.jfif"],
        introduceText:"FINE LINES & UNEVEN TEXTURE (₫‌3,256,200 VALUE)",
        productName:"DEWTOPIA NIGHTTIME DUO 5% ACID FIRMING NIGHT CRÈME & 20% ACID NIGHT TREATMENT",
        catalogue:"SERUM",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["3256200"],
        price:["2903400"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/CLEAR AS NIGHT SMOOTHING TRIO.jfif"],
        introduceText:"FINE LINES & UNEVEN TEXTURE (₫‌3,988,800 VALUE)",
        productName:"CLEAR AS NIGHT SMOOTHING TRIO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["3988800"],
        price:["3391900"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/DEEP CLEAN + SCRUB DUO.jfif"],
        introduceText:"OILY & BLEMISH-PRONE SKIN (₫‌1,845,200 VALUE)",
        productName:"DEEP CLEAN + SCRUB DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:5,
        size:[],
        originalPrice:["1845200"],
        price:["1546700"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/OLE ALL STARS SKINCARE SET.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌6,268,100 VALUE)",
        productName:"OLE ALL STARS SKINCARE SET",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["6268100"],
        price:["5372700"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/MAKEUP PREP SET.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌3,337,600 VALUE)",
        productName:"MAKEUP PREP SET",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:5,
        size:[],
        originalPrice:["3337600"],
        price:["2822000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW FOR A SPA DAY SKINCARE SET.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌3,446,100 VALUE)",
        productName:"GLOW FOR A SPA DAY SKINCARE SET",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:0,
        size:[],
        originalPrice:["3446100"],
        price:["2930600"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW2OH DARK SPOT TONNER DUO.jfif"],
        introduceText:"OILY & BLEMISH-PRONE SKIN (₫‌1,899,500 VALUE)",
        productName:"GLOW2OH DARK SPOT TONER DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[6.5],
        originalPrice:["1899500"],
        price:["1601000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/TRUTH SERUM DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌3,039,100 VALUE)",
        productName:"TRUTH SERUM DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["3039100"],
        price:["2550700"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/TONE AROUND THE CLOCK DAY & NIGHT.jfif"],
        introduceText:"OILY & BLEMISH-PRONE SKIN (₫‌1,899,500 VALUE)",
        productName:"TONER AROUND THE CLOCK DAY & NIGHT",
        catalogue:"TONER",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["1899500"],
        price:["1601000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GLOW MOTION 3-PIECE BRIGHTENING SET.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌4,043,100 VALUE)",
        productName:"GLOW MOTION 3-PIECE BRIGHTENING SET",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:5,
        size:[],
        originalPrice:["4043100"],
        price:["3473300"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/PHAT GLOW FACIAL.jfif"],
        introduceText:"",
        productName:"PHAT GLOW FACIAL",
        catalogue:"MOISTURIZER",
        status:"Available",
        rating:4.5,
        size:[1.7],
        originalPrice:[],
        price:["1411000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GFH (GLOW FROM HOME VITAMIN C DUO).jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,225,100 VALUE)",
        productName:"GFH (GLOW FROM HOME) VITAMIN C DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["2225100"],
        price:["1899500"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BEAMCREAM MOISTURIZER & FIRMLY YOURS DRY BODY OIL DUO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌2,252,200 VALUE)",
        productName:"BEAMCREAM MOISTURIZER & FIRMLY YOURS DRY BODY OIL DUO ",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4.5,
        size:[],
        originalPrice:["2252200"],
        price:["2008000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BANANA BRIGHT VITAMIN C TRIO.jfif"],
        introduceText:"DULLNESS & DRYNESS (₫‌4,124,500 VALUE)",
        productName:"BANANA BRIGHT VITAMIN C TRIO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4,
        size:[],
        originalPrice:["4124500"],
        price:["3473300"],
        quantity:1
    },
    {   
        productImg:["./Asset/Shop-all-product/BALANCING FORCE OIL CONTROL TONER DUO.jfif"],
        introduceText:"OILY & BLEMISH-PRONE SKIN (₫‌1,899,500 VALUE)",
        productName:"BALANCING FORCE OIL CONTROL TONER DUO",
        catalogue:"SET KIT",
        status:"Full Detail",
        rating:4,
        size:[],
        originalPrice:["1899500"],
        price:["1601000"],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/BALANCE IT ALL FULL-SIZE OIL CONTROL & PORE-REFINING SET.jfif"],
        introduceText:"OILY & BLEMISH-PRONE (₫‌3,201,900 VALUE)",
        productName:"BALANCE IT ALL FULL-SIZE OIL CONTROL & PORE-REFINING SET",
        catalogue:"SET KIT",
        status:"Available",
        rating:4,
        size:[],
        originalPrice:["3201900"],
        price:["2713500"],
        quantity:1
    } ,
    {
        productImg:["./Asset/Shop-all-product/BRIGHT FORM THE START DAILY SKINCARE ROUTINE.jfif"],
        introduceText:"ALL SKIN TYPES (₫‌1,302,500 VALUE)",
        productName:"BRIGHT FROM THE START DAILY SKINCARE ROUTINE",
        catalogue:"SET KIT",
        status:"Sold Out",
        rating:0,
        size:[],
        originalPrice:[],
        price:[""],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/JUMBO GLOW2OH DARK SPOT TONER.jfif"],
        introduceText:"BESTSELLER",
        productName:"JUMBO GLOW2OH DARK SPOT TONER",
        catalogue:"TONER",
        status:"Notify Me",
        rating:4.5,
        size:[10],
        originalPrice:[],
        price:[""],
        quantity:1
    },
    {
        productImg:["./Asset/Shop-all-product/GOODNIGHT GLOW RETIN-ALT SLEEPING CREME.jfif"],
        introduceText:"BESTSELLER",
        productName:"GOODNIGHT GLOW RETIN-ALT SLEEPING CRÈME",
        catalogue:"MOISTURIZER",
        status:"Notify Me",
        rating:4,
        size:[1.7],
        originalPrice:[],
        price:[""],
        quantity:1
    }  
]

function uuid(){
    return Math.ceil(Math.random()*9999999999+new Date().getMilliseconds());
}

for (let i = 0; i < products.length; i++) {
    products[i].id=[];
    if (products[i].size.length<=1) {
        products[i].id=uuid();
    }else {
        let productId = [];
        for (let j = 0; j < products[i].size.length; j++) {
            productId.push(uuid());
            products[i].id=productId;
        }
    }
    
}
localStorage.setItem("productsList",JSON.stringify(products));